Changed billy stanza

diff --git a/.github/workflows/main.yaml b/.github/workflows/main.yaml
--- a/.github/workflows/main.yaml
+++ b/.github/workflows/main.yaml
@@ -43,12 +43,12 @@ jobs:
       # Step 6: Manifest Generation (Optional, for Aqua Security integration)
       - name: Manifest Generation
         run: |
-          export BILLY_SERVER=https://billy.codesec.aquasec.com
+          export BILLY_SERVER=https://billy.eu-1.codesec.aquasec.com
           curl -sLo install.sh download.codesec.aquasec.com/billy/install.sh
           curl -sLo install.sh.checksum https://github.com/argonsecurity/releases/releases/latest/download/install.sh.checksum
-          if ! cat install.sh.checksum | sha256sum -c ; then
-            echo "install.sh checksum failed"
-            exit 1
+          if ! cat install.sh.checksum | sha256sum --check; then
+          echo "install.sh checksum failed"
+          exit 1
           fi
           BINDIR="." sh install.sh
           rm install.sh install.sh.checksum
@@ -56,11 +56,10 @@ jobs:
             --access-token "${{ secrets.GITHUB_TOKEN }}" \
             --aqua-key "${{ secrets.AQUA_KEY }}" \
             --aqua-secret "${{ secrets.AQUA_SECRET }}" \
-            --cspm-url "${{ env.CSPM_URL }}" \
-            --artifact-path "my-sample-app:${{ github.sha }}"
-        env:
-          CSPM_URL: https://eu-1.api.cloudsploit.com
-          AQUA_URL: https://api.eu-1.supply-chain.cloud.aquasec.com
-          AQUA_KEY: ${{ secrets.AQUA_KEY }}
-          AQUA_SECRET: ${{ secrets.AQUA_SECRET }}
-          GITHUB_TOKEN: ${{ github.token }}
+            --cspm-url https://eu-1.api.cloudsploit.com \
+            --artifact-path "my-image-name:${{ env.tag-version }}" 
+
+            # The docker image name:tag of the newly built image
+            # --artifact-path "my-image-name:${{ env.tag-version }}" 
+            # OR the path to the root folder of your project. I.e my-repo/my-app 
+            # --artifact-path "${{env.MY_APP_ROOT}}"
